# This file was generated by GoReleaser. DO NOT EDIT.
cask "boxed" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "846ff1aaeccf68e556f6748be6e1f00b3af76ad7c3dc5bb65aa3350fc824bdb5"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
    on_arm do
      sha256 "ff9793877b90218fcf31485150b3a74bcaba0835f4c83a6c6e28781bc2dca95b"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
  end

  on_linux do
    on_intel do
      sha256 "d67cc593cb63a8075e9de1689c7fb13caab02a3a73a7d57a58ff20dd5b1780f0"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
    on_arm do
      sha256 "5a080c485704c40f054b7cbde7a7030364c4c458c6eb7cf72e2cd9616a647d44"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
  end

  name "boxed"
  desc "Prints the effective Claude Code sandbox status as a colored statusline label"
  homepage "https://github.com/jamestelfer/boxed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boxed"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boxed"]
    end
  end

  # No zap stanza required

end
