# This file was generated by GoReleaser. DO NOT EDIT.
cask "boxed" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "9f497170260a7d523e17fc465202b4c01cb4d1db17203d1bcbb00b543c5ebafe"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
    on_arm do
      sha256 "258b15dd0139d623786147e482fc64b6f86e735a0a62781eae71fe16c7d676eb"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe4632fe90509137f9fff0ffdcd1c3071863da5a67a1b9fa144fae2baf9b27c8"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
    on_arm do
      sha256 "8bef4f63120097d9af932879265f23de44936d295e3e9185ed98ccac53f9adb2"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
  end

  name "boxed"
  desc "Prints the effective Claude Code sandbox status as a colored statusline label"
  homepage "https://github.com/jamestelfer/boxed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boxed"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boxed"]
    end
  end

  # No zap stanza required

end
