# This file was generated by GoReleaser. DO NOT EDIT.
cask "boxed" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "6689022168e3892b971d061d52884db34b6a56e2520afecee472466c10dc588a"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
    on_arm do
      sha256 "ef53147cc918b5b74b182cb8fc8a5ea34643b175775ed547c8140cbc4b582ad5"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
  end

  on_linux do
    on_intel do
      sha256 "33c29eb9b08f476836277998fe9995bfb7cf9ed3ff370b37350a276a720d9642"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
    on_arm do
      sha256 "cb71e4eac18be334a05a0779a87866712117d17e24d08ede5a37428fb4cbffdd"
      url "https://github.com/jamestelfer/boxed/releases/download/v#{version}/boxed_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/boxed"
    end
  end

  name "boxed"
  desc "Prints the effective Claude Code sandbox status as a colored statusline label"
  homepage "https://github.com/jamestelfer/boxed"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "boxed"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/boxed"]
    end
  end

  # No zap stanza required

end
