# This file was generated by GoReleaser. DO NOT EDIT.
cask "dollop" do
  version "1.4.0"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "35a85d3d7efc11da66487272259777de84b75566aa708c0fc5b79f43a0331bd1"
    end
    on_arm do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "61949540546b15e0ecf5d1c28e3b8755aea82cf79dfe9fc9cdf753716c1360e9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "75fc21f14f60c56b2f8949516c1da0e69cbbb80968f17f7f22a402881c5851b1"
    end
    on_arm do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "c56418784a32d8f6a3fd54ccbee371c8ce00c634c0fe2d45de440971e76656c9"
    end
  end

  name "dollop"
  desc "Upload files and directories to unique, expiring paths in Cloudflare R2"
  homepage "https://github.com/jamestelfer/dollop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dollop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dollop"]
    end
  end

  # No zap stanza required

end
