# This file was generated by GoReleaser. DO NOT EDIT.
cask "dollop" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/dollop"]
    end
  end

  version "1.13.0"

  on_macos do
    on_arm do
      sha256 "90b8b05d6935f3942e165029b490d7beb1147058d4af3ab7a177aaa70b763b3a"
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e2e53c91daeee223d599c594b59691e69e4881c94f079a3a87545da351910e5"
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b496bcf941619dc21ffc652ffa8baf12a82fe2920cacc25896b481e86bddb209"
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3aa6277e42a9da8a3ebac9afe8b746bc5f602f4753400aaeffba54331ff21332"
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_linux_amd64.tar.gz"
    end
  end

  name "dollop"
  desc "Upload files and directories to unique, expiring paths in Cloudflare R2"
  homepage "https://github.com/jamestelfer/dollop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dollop"

  # No zap stanza required
end
