# This file was generated by GoReleaser. DO NOT EDIT.
cask "dollop" do
  version "1.8.0"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "6361e7d249baa6a0743a2c577501bdf984198fe73c42c98c3d10b8eedf666b39"
    end
    on_arm do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "7542ddc0dcbf63a9d752bb7f20164e83393d279d2de9abfb5c9ea32a55b8aa46"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "752e26133c58d31a22ec2f51ebda0a588fe7a418eaae55f29a68ba0b4caf635e"
    end
    on_arm do
      url "https://github.com/jamestelfer/dollop/releases/download/v#{version}/dollop_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/dollop"
      sha256 "b7e541d5e2567ccde9b2009432d33b9cc592117c317353f79d87a2f60dd3676c"
    end
  end

  name "dollop"
  desc "Upload files and directories to unique, expiring paths in Cloudflare R2"
  homepage "https://github.com/jamestelfer/dollop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dollop"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dollop"]
    end
  end

  # No zap stanza required

end
