# This file was generated by GoReleaser. DO NOT EDIT.
cask "imds-broker" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "6791856a408b89e55c48a1388ae92829ad5691940e448a541c7b78d449166d5c"
    end
    on_arm do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "7c7dd1a9565a109547403a0083b889280fcb08e443c99d47688db44b80e32353"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "981bf9d0cc261b22fdb14df9feca2968af849972f68237fd2f518eb9d2ece09a"
    end
    on_arm do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "b7226cba7461ac8c074dd2ab65fe4ae3cd5df402cc087b928b9e4689022eba9e"
    end
  end

  name "imds-broker"
  desc "AWS IMDSv2-compatible credential server for local development and CI"
  homepage "https://github.com/jamestelfer/imds-broker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imds-broker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imds-broker"]
    end
  end

  # No zap stanza required

end
