# This file was generated by GoReleaser. DO NOT EDIT.
cask "imds-broker" do
  version "0.0.1-beta.1"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "eb0c717e7ee81ba3765e43d75ef00b35324c295c3aa804021c6b3cf2b55bb3c5"
    end
    on_arm do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "d22437324cfd43b9c95345a6c88241015e9dc6ea7ce0f575ad68f85d16b055ff"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "80157a3fd2e9f582cf7752d890dc8b7e799e39574c08d63da4ae8a1f5d9b0e7c"
    end
    on_arm do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "eae9579ac61d5ea8559ed6b958df7d82ca60248f47a0a434209e79f20278aad0"
    end
  end

  name "imds-broker"
  desc "AWS IMDSv2-compatible credential server for local development and CI"
  homepage "https://github.com/jamestelfer/imds-broker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imds-broker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imds-broker"]
    end
  end

  # No zap stanza required

end
