# This file was generated by GoReleaser. DO NOT EDIT.
cask "imds-broker" do
  version "0.0.1-beta.2"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_darwin_amd64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "31ca8ccd88f9df1d267950f9d90cea81dc1e4a79a9058d84b2712838ea9167f2"
    end
    on_arm do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_darwin_arm64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "84daa2d928721e42201c2392655b6b64e6e672f0bc7dad8454341dc7ab3cb83e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_linux_amd64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "98362fe33a485cc239d4e99a9bb8bd57425652c8b55f76c40baa3094a32e8b6b"
    end
    on_arm do
      url "https://github.com/jamestelfer/imds-broker/releases/download/v#{version}/imds-broker_linux_arm64.tar.gz",
        verified: "github.com/jamestelfer/imds-broker"
      sha256 "26be9126050f39f8599ab36b5272c351fa2f503c1e83f50794864b33fed6069d"
    end
  end

  name "imds-broker"
  desc "AWS IMDSv2-compatible credential server for local development and CI"
  homepage "https://github.com/jamestelfer/imds-broker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imds-broker"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/imds-broker"]
    end
  end

  # No zap stanza required

end
