# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandy" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-darwin-x64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "ea5cb1cf3127e8400d264ed2382e28e57ee716b0fcc148df754724934376f5a5"
    end
    on_arm do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "e181d3d8e69bbbc9edb8c87afb3a40657847d3232e556bac8881aceb5d329e9b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-linux-x64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "02d157f014ccd89015b9f9bce14e990f044e41820c25e80958a2ba46a8bb24d6"
    end
    on_arm do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-linux-arm64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "fe1df503c94b215c3bfb4272b75d106701eee80b344cb5b1b9fe714b84b71007"
    end
  end

  name "sandy"
  desc "Sandboxed TypeScript runtime with AWS SDK access for AI agents"
  homepage "https://github.com/jamestelfer/sandy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandy"]
      system_command "/usr/bin/codesign", args: ["--remove-signature", "#{staged_path}/sandy"], print_stderr: false, must_succeed: false
      system_command "/usr/bin/codesign", args: ["-s", "-", "--force", "#{staged_path}/sandy"]
    end
  end

  # No zap stanza required

end
