# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandy" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sandy"]
      run "/usr/bin/codesign", args: ["--remove-signature", "{{staged_path}}/sandy"], print_stderr: false, must_succeed: false
      run "/usr/bin/codesign", args: ["-s", "-", "--force", "{{staged_path}}/sandy"]
    end
  end

  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "3d3a77bc76d1b14b64a855e0d8af0edb004876932abc7eb1cb88e5fb79b5cb7c"
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f93891bce078882da2885bc63c3c16d76d1a2f3323b14e440a7fbecadbae5d23"
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-darwin-x64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "41e0e9f178590bfdc3de52e942bfd9f6d3c739842dff919a4ae422c49f205ed3"
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "ab673a9f72c78c6e856a060f65be88aaf811c29e2db82a819f999d7ff30e7ad7"
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-linux-x64.tar.gz"
    end
  end

  name "sandy"
  desc "Sandboxed TypeScript runtime with AWS SDK access for AI agents"
  homepage "https://github.com/jamestelfer/sandy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandy"

  # No zap stanza required
end
