# This file was generated by GoReleaser. DO NOT EDIT.
cask "sandy" do
  version "0.6.1"

  on_macos do
    on_intel do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-darwin-x64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "8422d4413dbb3b6b6b78d1e0562f3246282398d71cb6243d1edff021e2152c97"
    end
    on_arm do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "ec49fb40e182a48e5c6ef81ccff21bf4b7aa1bb173e1a195079453a341e2716f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-linux-x64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "225949105c40e0211e77a89e8ef0bae32e77df0c0832e1c7e90597e528f6e443"
    end
    on_arm do
      url "https://github.com/jamestelfer/sandy/releases/download/v#{version}/sandy-#{version}-linux-arm64.tar.gz",
        verified: "github.com/jamestelfer/sandy"
      sha256 "491185ea06bfef3c6a7121066d89ca7b8a23a92211de240d08a8ffc4268354c0"
    end
  end

  name "sandy"
  desc "Sandboxed TypeScript runtime with AWS SDK access for AI agents"
  homepage "https://github.com/jamestelfer/sandy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sandy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sandy"]
      system_command "/usr/bin/codesign", args: ["--remove-signature", "#{staged_path}/sandy"], print_stderr: false, must_succeed: false
      system_command "/usr/bin/codesign", args: ["-s", "-", "--force", "#{staged_path}/sandy"]
    end
  end

  # No zap stanza required

end
